---
title: "Ingest S3 Performance"
author: "Ajay Krishnamurthy"
output:
  pdf_document: default
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=6) 
```

```{r, echo=FALSE, warning =FALSE, message = FALSE}
library(tidyverse)
library(grid)
library(ggh4x)

```

```{r, echo=FALSE, warning = FALSE, message = FALSE}
data <- read_csv("results.csv")
data <- data |>
  mutate(MiB = paste0(MiB, "MiB"), fpt = paste0(fpt, " file(s) per task"), numfiles = paste0(numfiles, " file(s)"))

data <- data |>
  filter(fpt == "1 file(s) per task")

```


```{r, echo=FALSE, warning = FALSE, message = FALSE}
grouped_data <- data |>
  group_by(MiB, numfiles, delay, threads, fpt) |>
  summarize(
    median_runtime = median(seconds)
  )
```

```{r, echo=FALSE, warning =FALSE, message = FALSE}
one_mib <- grouped_data |>
  filter(MiB=="1MiB")

five_mib <- grouped_data |>
  filter(MiB=="5MiB")

ten_mib <- grouped_data |>
  filter(MiB=="10MiB")

hundred_mib <- grouped_data |>
  filter(MiB=="100MiB")

fivehundred_mib <- grouped_data |>
  filter(MiB=="500MiB")

one_gib <- grouped_data |>
  filter(MiB=="1000MiB")

five_gib <- grouped_data |>
  filter(MiB=="5000MiB")
```


```{r, echo=FALSE, warning =FALSE, message = FALSE}
pl <- one_mib %>%
  ggplot(aes(x = delay, y = median_runtime, color = as.factor(threads))) +
  geom_line() +
  geom_point(shape=1) +
  theme_light() +
  theme(strip.background = element_rect(color="black"), strip.text = element_text(size = 13, color = "black", angle = 0, hjust = 0.5), axis.ticks = element_line(size = 0.5, color = "black")) + 
  scale_color_discrete(name = "# Threads", labels = c("Streaming", "2", "3", "4", "8")) +
  labs(x = "Network RTT (milliseconds)", 
       y = "Median Execution Time (seconds)") +
  scale_y_continuous(limits = c(0, 35), breaks = seq(0, 35, 10))

strips <- strip_themed(
  background_x = elem_list_rect(fill = c("rosybrown1", "lightgreen")),
     by_layer_x = TRUE,
)
pl <- pl + facet_wrap2(~ MiB +  numfiles, strip=strips)
ggsave(file="one_mib.png", plot=pl, width=8, height=6)

pl
```


```{r, echo=FALSE, warning =FALSE, message = FALSE}
pl <- five_mib %>%
  ggplot(aes(x = delay, y = median_runtime, color = as.factor(threads))) +
  geom_line() +
  geom_point(shape=1) +
  theme_light() +
  theme(strip.background = element_rect(color="black"), strip.text = element_text(size = 13, color = "black", angle = 0, hjust = 0.5), axis.ticks = element_line(size = 0.5, color = "black")) + 
  scale_color_discrete(name = "# Threads", labels = c("Streaming", "2", "3", "4", "8")) +
  labs(x = "Network RTT (milliseconds)", 
       y = "Median Execution Time (seconds)") +
  scale_y_continuous(limits = c(0, 35), breaks = seq(0, 35, 10))

strips <- strip_themed(
  background_x = elem_list_rect(fill = c("rosybrown1", "lightgreen")),
     by_layer_x = TRUE,
)
pl <- pl + facet_wrap2(~ MiB +  numfiles, strip=strips)
ggsave(file="five_mib.png", plot=pl, width=8, height=6)

pl
```


```{r, echo=FALSE, warning =FALSE, message = FALSE}
pl <- ten_mib %>%
  ggplot(aes(x = delay, y = median_runtime, color = as.factor(threads))) +
  geom_line() +
  geom_point(shape=1) +
  theme_light() +
  theme(strip.background = element_rect(color="black"), strip.text = element_text(size = 13, color = "black", angle = 0, hjust = 0.5), axis.ticks = element_line(size = 0.5, color = "black")) + 
  scale_color_discrete(name = "# Threads", labels = c("Streaming", "2", "3", "4", "8")) +
  labs(x = "Network RTT (milliseconds)", 
       y = "Median Execution Time (seconds)") +
  scale_y_continuous(limits = c(0, 35), breaks = seq(0, 35, 10))

strips <- strip_themed(
  background_x = elem_list_rect(fill = c("rosybrown1", "lightgreen")),
     by_layer_x = TRUE,
)
pl <- pl + facet_wrap2(~ MiB +  numfiles, strip=strips)
ggsave(file="ten_mib.png", plot=pl, width=8, height=6)

pl

```

```{r, echo=FALSE, warning =FALSE, message = FALSE}
pl <- hundred_mib %>%
  ggplot(aes(x = delay, y = median_runtime, color = as.factor(threads))) +
  geom_line() +
  geom_point(shape=1) +
  theme_light() +
  theme(strip.background = element_rect(color="black"), strip.text = element_text(size = 13, color = "black", angle = 0, hjust = 0.5), axis.ticks = element_line(size = 0.5, color = "black")) + 
  scale_color_discrete(name = "# Threads", labels = c("Streaming", "2", "3", "4", "8")) +
  labs(x = "Network RTT (milliseconds)", 
       y = "Median Execution Time (seconds)") +
  scale_y_continuous(limits = c(0, 35), breaks = seq(0, 35, 10))

strips <- strip_themed(
  background_x = elem_list_rect(fill = c("rosybrown1", "lightgreen")),
     by_layer_x = TRUE,
)
pl <- pl + facet_wrap2(~ MiB +  numfiles, strip=strips)
ggsave(file="hundred_mib.png", plot=pl, width=8, height=6)

pl
```


```{r, echo=FALSE, warning =FALSE, message = FALSE}
pl <- fivehundred_mib %>%
  ggplot(aes(x = delay, y = median_runtime, color = as.factor(threads))) +
  geom_line() +
  geom_point(shape=1) +
  theme_light() +
  theme(strip.background = element_rect(color="black"), strip.text = element_text(size = 13, color = "black", angle = 0, hjust = 0.5), axis.ticks = element_line(size = 0.5, color = "black")) + 
  scale_color_discrete(name = "# Threads", labels = c("Streaming", "2", "3", "4", "8")) +
  labs(x = "Network RTT (milliseconds)", 
       y = "Median Execution Time (seconds)") +
  scale_y_continuous(limits = c(0, 35), breaks = seq(0, 35, 10))

strips <- strip_themed(
  background_x = elem_list_rect(fill = c("rosybrown1", "lightgreen")),
     by_layer_x = TRUE,
)
pl <- pl + facet_wrap2(~ MiB +  numfiles, strip=strips)
ggsave(file="fivehundred_mib.png", plot=pl, width=8, height=6)

pl
```

```{r, echo=FALSE, warning = FALSE, message = FALSE}
pl <- one_gib %>%
  ggplot(aes(x = delay, y = median_runtime, color = as.factor(threads))) +
  geom_line() +
  geom_point(shape=1) +
  theme_light() +
  theme(strip.background = element_rect(color="black"), strip.text = element_text(size = 13, color = "black", angle = 0, hjust = 0.5), axis.ticks = element_line(size = 0.5, color = "black")) + 
  scale_color_discrete(name = "# Threads", labels = c("Streaming", "2", "3", "4", "8")) +
  labs(x = "Network RTT (milliseconds)", 
       y = "Median Execution Time (seconds)") +
  scale_y_continuous(limits = c(0, 35), breaks = seq(0, 35, 10))

strips <- strip_themed(
  background_x = elem_list_rect(fill = c("rosybrown1", "lightgreen")),
     by_layer_x = TRUE,
)
pl <- pl + facet_wrap2(~ MiB +  numfiles, strip=strips)
ggsave(file="one_gib.png", plot=pl, width=8, height=6)

pl

```

```{r, echo=FALSE, warning = FALSE, message = FALSE}
pl <- five_gib %>%
  ggplot(aes(x = delay, y = median_runtime, color = as.factor(threads))) +
  geom_line() +
  geom_point(shape=1) +
  theme_light() +
  theme(strip.background = element_rect(color="black"), strip.text = element_text(size = 13, color = "black", angle = 0, hjust = 0.5), axis.ticks = element_line(size = 0.5, color = "black")) + 
  scale_color_discrete(name = "# Threads", labels = c("Streaming", "2", "3", "4", "8")) +
  labs(x = "Network RTT (milliseconds)", 
       y = "Median Execution Time (seconds)") +
  scale_y_continuous(limits = c(0, 50), breaks = seq(0, 50, 10))

strips <- strip_themed(
  background_x = elem_list_rect(fill = c("rosybrown1", "lightgreen")),
     by_layer_x = TRUE,
)
pl <- pl + facet_wrap2(~ MiB +  numfiles, strip=strips)
ggsave(file="five_gib.png", plot=pl, width=8, height=6)

pl

```

